#!/usr/bin/env bash
# OETP dev environment setup
# Generates device/ledger/beacon keys, writes dev/.env, and creates sample data.
set -euo pipefail

cd "$(dirname "$0")/.."

DEV_DIR="./dev"
mkdir -p "$DEV_DIR/cache" "$DEV_DIR/queue" "$DEV_DIR/ledger"

echo "generating device Ed25519 key..."
DEVICE_KEY=$(openssl genpkey -algorithm ed25519 -outform DER 2>/dev/null | tail -c 32 | xxd -p -c 64)
echo "$DEVICE_KEY" > "$DEV_DIR/device.key"
chmod 600 "$DEV_DIR/device.key"

echo "generating device X25519 key..."
DEVICE_X25519_KEY=$(openssl genpkey -algorithm x25519 -outform DER 2>/dev/null | tail -c 32 | xxd -p -c 64)
echo "$DEVICE_X25519_KEY" > "$DEV_DIR/device_x25519.key"
chmod 600 "$DEV_DIR/device_x25519.key"

echo "generating ledger signing key..."
LEDGER_KEY=$(openssl genpkey -algorithm ed25519 -outform DER 2>/dev/null | tail -c 32 | xxd -p -c 64)
echo "$LEDGER_KEY" > "$DEV_DIR/ledger.key"
chmod 600 "$DEV_DIR/ledger.key"

echo "generating beacon signing key..."
BEACON_KEYPAIR=$(cargo run --release -p oetp-ledger -- keygen 2>/dev/null)
BEACON_KEY=$(echo "$BEACON_KEYPAIR" | head -1)
BEACON_PUB=$(echo "$BEACON_KEYPAIR" | tail -1)
echo "$BEACON_KEY" > "$DEV_DIR/beacon.key"
chmod 600 "$DEV_DIR/beacon.key"

EXAM_SALT=$(openssl rand -hex 32)
SERVER_PEPPER=$(openssl rand -hex 32)
TENANT_MASTER_KEY=$(openssl rand -hex 32)

API_KEY="dev-api-key-12345678-with-enough-characters"

cat > "$DEV_DIR/.env" <<ENVEOF
# OETP Development Environment - auto-generated by dev/setup.sh
# shellcheck disable=all

# === Edge Daemon ===
OETP_TENANT_ID=nta
OETP_EXAM_ID=jee-2027
OETP_DEVICE_ID=device-01
OETP_CENTER_ID=center-01
OETP_LEDGER_URL=http://localhost:8081
OETP_BEACON_URL=http://localhost:9090
OETP_LISTEN_ADDR=127.0.0.1:8080
OETP_DEVICE_KEY=${PWD}/dev/device.key
OETP_DEVICE_X25519_KEY=${PWD}/dev/device_x25519.key
OETP_CACHE_DIR=${PWD}/dev/cache
OETP_QUEUE_DIR=${PWD}/dev/queue
OETP_BEACON_PUBLIC_KEY=${BEACON_PUB}
OETP_EXAM_SALT=${EXAM_SALT}
OETP_SERVER_PEPPER=${SERVER_PEPPER}
OETP_API_KEY=${API_KEY}

# === Ledger ===
OETP_LEDGER_LISTEN_ADDR=0.0.0.0:8081
OETP_LEDGER_DB_PATH=${PWD}/dev/ledger.db
OETP_SIGNING_KEY=${LEDGER_KEY}
OETP_ANCHOR_RPC_URL=http://localhost:8545

# === Beacon ===
OETP_BEACON_LISTEN_ADDR=0.0.0.0:9090
OETP_BEACON_SIGNING_KEY=${BEACON_KEY}

# === Shared ===
OETP_TENANT_MASTER_KEY=${TENANT_MASTER_KEY}

# === Logging ===
RUST_LOG=info
ENVEOF

chmod 600 "$DEV_DIR/.env"
echo "wrote $DEV_DIR/.env"

cat > "$DEV_DIR/question_bank.json" <<'QBEOF'
[
  {"id":1,"difficulty":"Easy","stem":"What is the capital of France?","variants":[{"id":0,"substitutions":{},"options":["London","Paris","Berlin","Madrid"],"correct_index":1}]},
  {"id":2,"difficulty":"Easy","stem":"What is 2+2?","variants":[{"id":0,"substitutions":{},"options":["3","4","5","6"],"correct_index":1}]},
  {"id":3,"difficulty":"Easy","stem":"Which planet is known as the Red Planet?","variants":[{"id":0,"substitutions":{},"options":["Venus","Mars","Jupiter","Saturn"],"correct_index":1}]},
  {"id":4,"difficulty":"Easy","stem":"What is the chemical symbol for water?","variants":[{"id":0,"substitutions":{},"options":["H2O","CO2","NaCl","O2"],"correct_index":0}]},
  {"id":5,"difficulty":"Easy","stem":"How many continents are there?","variants":[{"id":0,"substitutions":{},"options":["5","6","7","8"],"correct_index":2}]},
  {"id":6,"difficulty":"Medium","stem":"What is the square root of 144?","variants":[{"id":0,"substitutions":{},"options":["10","11","12","13"],"correct_index":2}]},
  {"id":7,"difficulty":"Medium","stem":"Who wrote Romeo and Juliet?","variants":[{"id":0,"substitutions":{},"options":["Dickens","Shakespeare","Austen","Hemingway"],"correct_index":1}]},
  {"id":8,"difficulty":"Medium","stem":"What is the speed of light in m/s?","variants":[{"id":0,"substitutions":{},"options":["3e8","3e6","3e10","3e4"],"correct_index":0}]},
  {"id":9,"difficulty":"Medium","stem":"Which element has atomic number 6?","variants":[{"id":0,"substitutions":{},"options":["Nitrogen","Oxygen","Carbon","Boron"],"correct_index":2}]},
  {"id":10,"difficulty":"Medium","stem":"What is the largest ocean?","variants":[{"id":0,"substitutions":{},"options":["Atlantic","Indian","Arctic","Pacific"],"correct_index":3}]},
  {"id":11,"difficulty":"Hard","stem":"What is the integral of 1/x?","variants":[{"id":0,"substitutions":{},"options":["ln|x|+C","e^x+C","x^2/2+C","1/x^2+C"],"correct_index":0}]},
  {"id":12,"difficulty":"Hard","stem":"What is the Heisenberg Uncertainty Principle?","variants":[{"id":0,"substitutions":{},"options":["ΔxΔp≥ℏ/2","E=mc²","F=ma","PV=nRT"],"correct_index":0}]},
  {"id":13,"difficulty":"Hard","stem":"What is the time complexity of quicksort?","variants":[{"id":0,"substitutions":{},"options":["O(n)","O(n log n)","O(n²)","O(log n)"],"correct_index":1}]},
  {"id":14,"difficulty":"Hard","stem":"What is the oxidation state of Mn in KMnO4?","variants":[{"id":0,"substitutions":{},"options":["+5","+6","+7","+4"],"correct_index":2}]},
  {"id":15,"difficulty":"Hard","stem":"What is the Laplace transform of 1?","variants":[{"id":0,"substitutions":{},"options":["1/s","s","e^s","1"],"correct_index":0}]}
]
QBEOF
echo "wrote $DEV_DIR/question_bank.json"

cat > "$DEV_DIR/students.csv" <<'STUEOF'
550e8400-e29b-41d4-a716-446655440000,device-01
550e8400-e29b-41d4-a716-446655440001,device-01
STUEOF
echo "wrote $DEV_DIR/students.csv"

echo ""
echo "=== Setup complete ==="
echo "source $DEV_DIR/.env to load environment"
echo "then: cargo run -p oetp-ledger -- serve"
echo "      cargo run -p oetp-beacon"
echo "      cargo run -p oetp-edge"
